### PR TITLE
Dark mode

### PR DESCRIPTION
**Pull request by rozPierog**
I've added dark mode to this app, complete with option to change in Settings.
@PeterCxy my only problem with implementatnio is that after theme change there is something wrong with rerendering activity, can you help me with that?

### CODE REVIEW

**Comment by dimqua** [comment]
@PeterCxy ping

**Comment by thecrazyblack** [comment]
@PeterCxy ping

**Comment by PeterCxy** [comment]
please do not keep boosting the pull request. I will get back to development soon as I have said in the pinned issues

**Comment by noah-yac** [comment]
I am waiting patiently for dark mode, if its still happening

**Comment by PeterCxy** [comment]
@noah-yac It will be happening, but no longer through something like this PR. I will be making Shelter compatible with the new Monet themes on Android 12.

**Pull request closed without merging**
